module.exports = {
  TWILIO_AUTH_TOKEN: '',
  TWILIO_DEFAULT_VOIP_PHONE_NUMBER: '',
  TWILIO_ACCOUNT_SID: '',
  TWILIO_DEFAULT_CUSTOMER_NUMBER: '',
  YELP_CLIENT_ID: '',
  YELP_CLIENT_SECRET: '',
  YELP_ACCESS_TOKEN: '',
};
